version: '3.3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8081:8081"
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    ports:
     - "5000:5000"